### ISSUE TITLE
Doing it Wrong: WP_User_Query:query was called incorrectly

### ISSUE THREAD

**Issue by sangeetha-nayak** [newfold-labs/wp-module-loader#4]
**Summarize the issue (briefly)**
Function WP_User_Query::query was called incorrectly. User queries should not be run before the plugins_loaded hook PHP notice is shown for following usage
1. NewfoldLabs\W\M\container()
wp-content/plugins/dist/vendor/newfold-labs/wp-module-loader/includes/functions.php:105

**Steps to reproduce**
  1. On latest plugin dashboard, via Query Monitor

**Screenshots**
![Screenshot (524)](https://github.com/newfold-labs/wp-module-loader/assets/138747461/b022a2dd-dbfd-40bb-adea-989e405ba1a0)
![Screenshot (525)](https://github.com/newfold-labs/wp-module-loader/assets/138747461/5ddad60a-2a66-48a8-b0e6-dffd979fa699)

**Bluehost Plugin Version:**
* Version: 3.9.4 Latest

**Browser (with version) & Operating System (with version)**

  Browser: Chrome
  Operating System: Win 10
  Device: WIndows

**Comment by sangeetha-nayak** [comment]
Its already raised on activation module as well. Please check this [#4](https://github.com/newfold-labs/wp-module-activation/issues/4)

**Comment by wpscholar** [comment]
Closing this as it should be resolved once https://github.com/newfold-labs/wp-module-activation/pull/7/ is merged.
